version: "3.8"
services:                 
    backend-fastapi:
        build:
            context: ./app_fastapi
            dockerfile: Dockerfile_fastapi
        container_name: etf_fastapi 
        image: img_fastapi_etf:v01 
        environment:
            TZ: Asia/Taipei                        
        ports:
            - "5008:80"            
    frontend-plotly:
        build:
            context: ./app_plotly
            dockerfile: Dockerfile_plotly
        container_name: etf_plotly 
        image: img_dash_plotly:v01 
        environment:
            TZ: Asia/Taipei 
        ports:
            - "8080:8050" 
        depends_on:
            - backend-fastapi  
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile_ngnix
        container_name: nginx_plotly
        image: nginx:alpine
        ports:
            - "80:80"
        depends_on:
            - frontend-plotly     
        