FROM python:3.11

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./api_gate /code/api_gate 
COPY ./api_database /code/api_database
COPY ./.env.dev /code
COPY ./main.py /code

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]